### ISSUE TITLE
reporting 16.x as current LTS but support for it has ended

### ISSUE THREAD

**Issue by Trott** [pkgjs/action#62]
16.x support ended 9 days ago, but `.github/actions/prepare-node-test-matrix-action` is still reporting it as LTS (unless I'm doing something wrong, of course).

You can see this from the command line by running `node index.js` from the `.github/actions/prepare-node-test-matrix-action` directory. You can also see it in the GitHub Action output at https://github.com/nodejs/citgm/actions/runs/6244928993/job/16965961626?pr=959 (expand the output for "Prepare the matrix"):

<img width="442" alt="image" src="https://github.com/pkgjs/action/assets/718899/ec88bf27-0ab5-4640-82dd-a17e96880cd0">

I expect 16.x to show up as unsupported, but it doesn't.

**Comment by Trott** [comment]
Oh, I wonder if I'm misunderstanding how this works. "unsupported" might mean "unsupported according to the 'engines' setting in package.json" in which case...I guess this is right.

**Comment by dominykas** [comment]
> Oh, I wonder if I'm misunderstanding how this works. "unsupported" might mean "unsupported according to the 'engines' setting in package.json" in which case...I guess this is right.

Yes, this is the case. We can probably revisit the wording there to clarify this 👍 

> 16.x support ended 9 days ago, but .github/actions/prepare-node-test-matrix-action is still reporting it as LTS (unless I'm doing something wrong, of course).

The build matrix will not automatically remove versions from the matrix (that would be a breaking change for the consumers). We can also maybe revisit the wording here, i.e. explain that we're running this because it was once LTS and it is still in the `engines` range, but is no longer LTS. OTOH, it may not be worth doing, because it could be considered as a nudge to drop support for old versions, and I know there'd definitely be opinions against such a nudge.
